"ui.background" = { bg = "base" }
"ui.cursor" = { bg = "muted" }
"ui.cursor.match" = { bg = "match" }
"ui.linenr" = { fg = "muted" }
"ui.bufferline" = { fg = "muted", bg = "base" }
"ui.bufferline.active" = { fg = "text", bg = "overlay" }
"ui.statusline" = { fg = "text", bg = "surface" }
"ui.statusline.inactive" = { fg = "muted", bg = "base" }
"ui.popup" = { bg = "surface" }
"ui.menu" = { fg = "text", bg = "surface" }
"ui.selection" = { bg = "visual" }

"warning" = "gold"
"error" = "love"
"info" = "foam"
"hint" = "hint"
"debug" = "rose"
"type" = "foam"
"type.builtin" = { fg = "builtin", modifiers = ["bold"] }
"constant" = "constant"
"constant.builtin.boolean" = { fg = "number", modifiers = ["bold"] }
"constant.numeric" = "number"
"string" = "string"
"comment" = { fg = "muted" }
"variable" = "text"
"variable.parameter" = "iris"
"variable.other.member" = "builtin"
"keyword" = "pine"
"operator" = "operator"
"function" = "rose"
"function.method" = "foam"

[palette]
base = "#141415"
surface = "#1c1c24"
overlay = "#252530"
visual = "#333738"
muted = "#606079"
operator = "#90a0b5"
property = "#c3c3d5"
constant = "#aeaed1"
text = "#cdcdcd"
love = "#d8647e"
gold = "#f3be7c"
string = "#e8b589"
number = "#e0a363"
rose = "#c48282"
pine = "#6e94b2"
hint = "#7e98e8"
match = "#405065"
foam = "#9bb4bc"
builtin = "#b4d4cf"
iris = "#bb9dbd"
floatBorder = "#878787"
